[project]
name = "quick-word"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "bpython>=0.25",
    "pdbpp>=0.11.6",
    "pytest>=8.3.5",
]
